/** Self-contained starter: edit the HTML, CSS and JS directly in the CMS. */
export const INTERACTIVE_EXAMPLE = [
  '```interactive title="Small changes compound" description="Move the slider to see how a daily improvement adds up over a year." height=360',
  '<style>',
  '  .comparison { display:grid; grid-template-columns:1fr 1fr; gap:16px; margin:24px 0; }',
  '  .value { display:block; font-size:clamp(28px,8vw,48px); letter-spacing:-.05em; line-height:1.2; margin:8px 0; }',
  '  .track { height:8px; background:var(--soft); border-radius:8px; overflow:hidden; }',
  '  .fill { height:100%; background:var(--accent); transform-origin:left; transition:transform 180ms ease-out; }',
  '  .muted { color:var(--muted); font-size:14px; }',
  '</style>',
  '<label for="improvement">Daily improvement: <strong id="rate">0.5%</strong></label>',
  '<input id="improvement" type="range" min="0" max="1" step="0.1" value="0.5" aria-describedby="explanation">',
  '<div class="comparison">',
  '  <div><span class="muted">Starting point</span><strong class="value">1×</strong><div class="track"><div class="fill" style="transform:scaleX(0.026)"></div></div></div>',
  '  <div><span class="muted">After one year</span><output id="result" class="value" aria-live="polite">6.2×</output><div class="track"><div id="growth" class="fill" style="transform:scaleX(0.164)"></div></div></div>',
  '</div>',
  '<p id="explanation" class="muted">A simple model: (1 + daily improvement) raised to 365. Real progress is less predictable; this illustrates the effect of compounding.</p>',
  '<script>',
  '  const slider = document.getElementById("improvement");',
  '  slider.addEventListener("input", () => {',
  '    const rate = Number(slider.value);',
  '    const growth = Math.pow(1 + rate / 100, 365);',
  '    document.getElementById("rate").textContent = rate.toFixed(1) + "%";',
  '    document.getElementById("result").textContent = growth.toFixed(1) + "×";',
  '    document.getElementById("growth").style.transform = "scaleX(" + growth / Math.pow(1.01, 365) + ")";',
  '  });',
  '</script>',
  '```',
].join('\n');
